name: Deploy

on:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Move to Home folder
        working-directory: Home
        run: npm install

      - name: Run App
        working-directory: Home
        run: node index.js  # or whatever your main file is
